[workspace]
resolver = "3"
members = ["crates/wnm-cli","crates/wnm-core"]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
wnm-core = { path = "crates/wnm-core" }

anyhow = "1.0.99"
core-foundation = "0.10.1"
core-graphics = "0.25.0"
