[package]
name = "resize_key_core"
version = "0.1.0"
build = "build.rs"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
core-foundation = "0.10.1"
core-graphics = "0.25.0"

[build-dependencies]
cc = "1.0"
