[package]
name = "resize_key_cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "resize"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
core.workspace = true

clap = { version = "4.5.47", features = ["derive"] }
